#!/usr/bin/env bash
set -euo pipefail

umask 077

log() { printf '[corepost-install] %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    die "run as root (or via sudo)"
  fi
}

read_prompt() {
  local var="$1"
  local prompt="$2"
  local default="${3:-}"
  local val=""
  if [ -n "$default" ]; then
    read -r -p "$prompt [$default]: " val </dev/tty || true
    val="${val:-$default}"
  else
    read -r -p "$prompt: " val </dev/tty || true
  fi
  printf -v "$var" '%s' "$val"
}

read_secret() {
  local var="$1"
  local prompt="$2"
  local val=""
  read -r -s -p "$prompt: " val </dev/tty || true
  printf '\n' >/dev/tty
  printf -v "$var" '%s' "$val"
}

read_prompt_optional() {
  local var="$1"
  local prompt="$2"
  local val=""
  read -r -p "$prompt: " val </dev/tty || true
  printf -v "$var" '%s' "$val"
}

confirm() {
  local prompt="$1"
  local ans=""
  read -r -p "$prompt [y/N]: " ans </dev/tty || true
  case "${ans:-}" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

raw_url() {
  local repo="$1"
  local ref="$2"
  local path="$3"

  local host="${COREPOST_GITHUB_RAW_HOST:-raw.githubusercontent.com}"
  local org="${COREPOST_GITHUB_ORG:-CorePost}"
  printf 'https://%s/%s/%s/%s/%s' "$host" "$org" "$repo" "$ref" "$path"
}

download() {
  local url="$1"
  local out="$2"
  require_cmd curl
  curl -fsS -L "$url" -o "$out"
}

rand_hex() {
  # shellcheck disable=SC2312
  openssl rand -hex "${1:-8}"
}

json_escape() {
  # Minimal JSON string escaper for our controlled inputs (hostname, machine-id, etc).
  # Escapes backslash and double-quote.
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

json_get() {
  # Extracts a top-level string field from a JSON object.
  # This is intentionally minimal (installer expects simple string keys).
  local key="$1"
  local val=""
  val="$(sed -n "s/.*\\\"${key}\\\":\\\"\\([^\\\"]*\\)\\\".*/\\1/p" | head -n 1)"
  [ -n "$val" ] || return 2
  printf '%s\n' "$val"
}

state_dir="${COREPOST_STATE_DIR:-/var/lib/corepost-install}"
runtime_dir="${COREPOST_RUNTIME_DIR:-/etc/corepost-install}"
preboot_conf="${COREPOST_PREBOOT_CONF:-/etc/corepost-preboot.conf}"
provisioning_path="${COREPOST_PROVISIONING_JSON:-/var/lib/corepost-install/provisioning.json}"
agent_env_path="${COREPOST_AGENT_ENV:-/etc/corepost-agent.env}"
agent_provisioning_path="${COREPOST_AGENT_PROVISIONING_JSON:-/var/lib/corepost-install/agent-provisioning.json}"

ensure_dirs() {
  mkdir -p "$state_dir" "$runtime_dir"
  chmod 0700 "$state_dir" "$runtime_dir"
}

conf_get() {
  # Reads KEY="value" from a shell-style config file.
  local file="$1"
  local key="$2"
  [ -f "$file" ] || return 1
  # shellcheck disable=SC2002
  cat "$file" | sed -n "s/^${key}=\"\\(.*\\)\"$/\\1/p" | head -n 1
}

load_provisioning_bundle() {
  local path="${1:-$provisioning_path}"
  [ -f "$path" ] || return 1
  cat "$path"
}

save_provisioning_bundle() {
  local path="${1:-$provisioning_path}"
  local bundle="${2:-}"
  [ -n "$bundle" ] || return 1
  printf '%s\n' "$bundle" >"$path"
  chmod 0600 "$path"
}

write_agent_env() {
  local server_url="$1"
  local device_id="$2"
  local device_secret="$3"

  [ -n "$server_url" ] || die "agent server url is empty"
  [ -n "$device_id" ] || die "agent device id is empty"
  [ -n "$device_secret" ] || die "agent device secret is empty"

  log "Writing agent env to $agent_env_path"
  cat >"$agent_env_path" <<EOF
# Generated by corepost-install.
COREPOST_SERVER_URL="${server_url}"
COREPOST_DEVICE_ID="${device_id}"
COREPOST_DEVICE_SECRET="${device_secret}"
COREPOST_AGENT_POLL_INTERVAL_SECONDS="60"
EOF
  chmod 0600 "$agent_env_path"
}

agent_env_is_valid() {
  [ -f "$agent_env_path" ] || return 1
  local url="" id="" secret=""
  url="$(conf_get "$agent_env_path" COREPOST_SERVER_URL || true)"
  id="$(conf_get "$agent_env_path" COREPOST_DEVICE_ID || true)"
  secret="$(conf_get "$agent_env_path" COREPOST_DEVICE_SECRET || true)"
  [ -n "$url" ] || return 1
  [ -n "$id" ] || return 1
  [ -n "$secret" ] || return 1
  case "$url$id$secret" in
    *"__SET_ME__"*) return 1 ;;
  esac
  return 0
}

register_device() {
  local server_url="$1"
  local admin_token="$2"
  local unlock_profile="$3"
  local usb_key_id="${4:-}"

  local display_name="${COREPOST_DISPLAY_NAME:-$(hostname -s 2>/dev/null || echo corepost)}"
  local hwid=""
  if [ -f /etc/machine-id ]; then
    hwid="$(tr -d '\n' </etc/machine-id || true)"
  fi

  local payload=""
  local dn_escaped hwid_escaped usb_escaped
  dn_escaped="$(json_escape "$display_name")"
  hwid_escaped="$(json_escape "$hwid")"
  usb_escaped="$(json_escape "$usb_key_id")"

  payload="{\"displayName\":\"${dn_escaped}\",\"unlockProfile\":\"${unlock_profile}\",\"userCanUnlock\":true,\"agentAction\":\"observe\""
  if [ -n "$hwid" ]; then
    payload="${payload},\"hwid\":\"${hwid_escaped}\""
  fi
  if [ -n "$usb_key_id" ]; then
    payload="${payload},\"usbKeyId\":\"${usb_escaped}\""
  fi
  payload="${payload}}"

  log "Registering device on server..."
  local resp
  resp="$(curl -fsS -X POST \
    -H "Content-Type: application/json" \
    -H "X-Admin-Token: $admin_token" \
    --data "$payload" \
    "${server_url%/}/admin/register")" || die "device registration failed"

  printf '%s\n' "$resp"
}

write_preboot_conf() {
  local server_url="$1"
  local device_id="$2"
  local device_secret="$3"
  local unlock_profile="$4"

  local usb_key_path="${COREPOST_USB_KEY_PATH:-/dev/disk/by-label/COREPOST_USB}"
  local luks_device="${COREPOST_LUKS_DEVICE:-/dev/corepost-preboot-demo-luks}"
  local luks_name="${COREPOST_LUKS_NAME:-corepost-demo-crypt}"

  log "Writing preboot config to $preboot_conf"
  cat >"$preboot_conf" <<EOF
# Generated by corepost-install.
COREPOST_SERVER_URL="${server_url}"
COREPOST_DEVICE_ID="${device_id}"
COREPOST_DEVICE_SECRET="${device_secret}"
COREPOST_UNLOCK_PROFILE="${unlock_profile}"
COREPOST_USB_KEY_PATH="${usb_key_path}"
COREPOST_NETWORK_IFACE="auto"
COREPOST_NETWORK_TIMEOUT_SECONDS="20"
COREPOST_NETWORK_FAILURE_POLICY="deny"
COREPOST_REQUEST_RETRIES="3"
COREPOST_REQUEST_RETRY_DELAY_SECONDS="2"
COREPOST_SERVER_CONNECT_TIMEOUT_SECONDS="5"
COREPOST_SERVER_MAX_TIME_SECONDS="20"
COREPOST_LUKS_DEVICE="${luks_device}"
COREPOST_LUKS_NAME="${luks_name}"
EOF
  chmod 0600 "$preboot_conf"
}

install_preboot_runtime() {
  local ref="${COREPOST_PREBOOT_REF:-main}"
  local repo="${COREPOST_PREBOOT_REPO:-corepost-preboot}"

  local hook_url script_url
  hook_url="$(raw_url "$repo" "$ref" "initramfs-tools/hooks/corepost-preboot")"
  script_url="$(raw_url "$repo" "$ref" "initramfs-tools/scripts/local-top/corepost-preboot")"

  log "Downloading preboot runtime from raw GitHub (ref=$ref)..."
  local tmp
  tmp="$(mktemp -d)"

  download "$hook_url" "$tmp/corepost-preboot-hook"
  download "$script_url" "$tmp/corepost-preboot-script"

  install -D -m 0755 "$tmp/corepost-preboot-hook" /etc/initramfs-tools/hooks/corepost-preboot
  install -D -m 0755 "$tmp/corepost-preboot-script" /etc/initramfs-tools/scripts/local-top/corepost-preboot

  log "Updating initramfs..."
  require_cmd update-initramfs
  update-initramfs -u

  rm -rf "$tmp"
}

install_agent_stub() {
  local ref="${COREPOST_AGENT_REF:-main}"
  local repo="${COREPOST_AGENT_REPO:-corepost-agent}"
  local agent_server_url="${1:-}"
  local agent_device_id="${2:-}"
  local agent_device_secret="${3:-}"

  local unit_url script_url env_url
  unit_url="$(raw_url "$repo" "$ref" "dist/corepost-agent.service")"
  script_url="$(raw_url "$repo" "$ref" "dist/corepost-agent.sh")"
  env_url="$(raw_url "$repo" "$ref" "dist/corepost-agent.env.example")"

  log "Downloading agent stub from raw GitHub (ref=$ref)..."
  local tmp
  tmp="$(mktemp -d)"

  download "$unit_url" "$tmp/corepost-agent.service"
  download "$script_url" "$tmp/corepost-agent.sh"
  download "$env_url" "$tmp/corepost-agent.env.example" || true

  install -D -m 0644 "$tmp/corepost-agent.service" /etc/systemd/system/corepost-agent.service
  install -D -m 0755 "$tmp/corepost-agent.sh" /usr/local/lib/corepost-agent/corepost-agent.sh

  if [ -n "$agent_server_url" ] && [ -n "$agent_device_id" ] && [ -n "$agent_device_secret" ]; then
    write_agent_env "$agent_server_url" "$agent_device_id" "$agent_device_secret"
  else
    log "Agent config is missing; not writing $agent_env_path"
    rm -f "$agent_env_path" >/dev/null 2>&1 || true
  fi

  if command -v systemctl >/dev/null 2>&1; then
    log "Enabling agent service and reloading it..."
    systemctl daemon-reload
    if agent_env_is_valid; then
      systemctl enable corepost-agent.service >/dev/null 2>&1 || true
      # Ensure the running service reloads unit and EnvironmentFile changes.
      if systemctl is-active --quiet corepost-agent.service; then
        systemctl restart corepost-agent.service || die "failed to restart corepost-agent.service"
      else
        systemctl start corepost-agent.service || die "failed to start corepost-agent.service"
      fi
    else
      log "Agent env is not valid; not starting corepost-agent.service"
      systemctl disable corepost-agent.service >/dev/null 2>&1 || true
      systemctl stop corepost-agent.service >/dev/null 2>&1 || true
    fi
  else
    log "systemctl not available; skipping service enable"
  fi

  rm -rf "$tmp"
}

list_removable_block_devices() {
  # NAME TRAN RM TYPE SIZE MODEL
  # Only allow "disk" devices, exclude optical media (rom), loop, etc.
  lsblk -pnro NAME,TRAN,RM,TYPE,SIZE,MODEL 2>/dev/null | awk '($4 == "disk") && ($3 == 1 || $2 == "usb") {print $1, $2, $3, $5, $6}'
}

setup_3fa_usb_factor() {
  log "Looking for removable block devices..."
  local candidates
  candidates="$(list_removable_block_devices || true)"
  if [ -z "${candidates:-}" ]; then
    die "no removable block devices found for 3FA"
  fi

  printf '%s\n' "$candidates" >&2
  local dev=""
  read_prompt dev "Enter device path to use as USB factor (this will be wiped)"
  [ -b "$dev" ] || die "not a block device: $dev"
  confirm "Wipe and format $dev with label COREPOST_USB?" || die "aborted by user"

  require_cmd mkfs.ext4
  mkfs.ext4 -F -L COREPOST_USB "$dev" >/dev/null
  if command -v udevadm >/dev/null 2>&1; then
    udevadm settle || true
  fi
  log "USB factor prepared (label COREPOST_USB)"
}

vm_demo_clean() {
  local luks_name="${COREPOST_LUKS_NAME:-corepost-demo-crypt}"
  if command -v cryptsetup >/dev/null 2>&1; then
    cryptsetup close "$luks_name" >/dev/null 2>&1 || true
  fi

  if command -v losetup >/dev/null 2>&1; then
    # Best-effort cleanup: detach any loop devices that point to our state dir.
    # This covers cases where the backing file was deleted or the state file is missing.
    losetup -a 2>/dev/null | awk -F: -v root="$state_dir" 'index($0, root) {print $1}' | while read -r loop; do
      [ -n "$loop" ] || continue
      losetup -d "$loop" >/dev/null 2>&1 || true
    done

    if [ -f "$state_dir/demo/luks.loop" ]; then
      local loop=""
      loop="$(cat "$state_dir/demo/luks.loop" 2>/dev/null || true)"
      if [ -n "$loop" ]; then
        losetup -d "$loop" >/dev/null 2>&1 || true
      fi
    fi
  fi

  rm -f "${COREPOST_LUKS_DEVICE:-/dev/corepost-preboot-demo-luks}" || true
  rm -rf "$state_dir/demo" || true
}

vm_demo_prepare_luks() {
  local user_password="$1"
  local unlock_token="$2"

  require_cmd cryptsetup
  require_cmd losetup
  require_cmd truncate

  local luks_device="${COREPOST_LUKS_DEVICE:-/dev/corepost-preboot-demo-luks}"
  local luks_name="${COREPOST_LUKS_NAME:-corepost-demo-crypt}"

  mkdir -p "$state_dir/demo"
  chmod 0700 "$state_dir/demo"

  local luks_image="$state_dir/demo/demo-luks.img"
  truncate -s 256M "$luks_image"
  local loop
  loop="$(losetup --find --show "$luks_image")"
  printf '%s\n' "$loop" >"$state_dir/demo/luks.loop"

  local combined="${user_password}${unlock_token}"
  printf '%s' "$combined" | cryptsetup luksFormat "$loop" --batch-mode --type luks2 --key-file=-
  ln -sf "$loop" "$luks_device"

  log "Demo LUKS device prepared at $luks_device"
}

vm_demo_run_preboot() {
  local user_password="$1"
  local luks_name="${COREPOST_LUKS_NAME:-corepost-demo-crypt}"

  log "Running preboot script (userspace invocation) to validate decrypt..."
  printf '%s\n' "$user_password" | COREPOST_PREBOOT_CONFIG_FILE="$preboot_conf" /etc/initramfs-tools/scripts/local-top/corepost-preboot

  if cryptsetup status "$luks_name" >/dev/null 2>&1; then
    log "PASS: mapping $luks_name is open"
  else
    die "FAIL: mapping $luks_name is not open"
  fi
}

cmd_install() {
  require_root
  require_cmd curl
  require_cmd openssl
  require_cmd sed

  ensure_dirs

  local preboot_server_url="${COREPOST_PREBOOT_SERVER_URL:-${COREPOST_SERVER_URL:-}}"
  if [ -z "$preboot_server_url" ]; then
    read_prompt preboot_server_url "Preboot server base URL (scheme://host:port)"
  fi
  local preboot_admin_token="${COREPOST_PREBOOT_ADMIN_TOKEN:-${COREPOST_ADMIN_TOKEN:-}}"
  if [ -z "$preboot_admin_token" ]; then
    read_secret preboot_admin_token "Preboot admin token"
  fi

  local unlock_profile="2fa"
  local usb_key_id=""
  if confirm "Enable 3FA (requires a removable device labeled COREPOST_USB)?" ; then
    unlock_profile="3fa"
    usb_key_id="corepost-usb-$(rand_hex 8)"
    setup_3fa_usb_factor
  fi

  local preboot_bundle
  preboot_bundle="$(register_device "$preboot_server_url" "$preboot_admin_token" "$unlock_profile" "$usb_key_id")"
  save_provisioning_bundle "$provisioning_path" "$preboot_bundle"
  log "Saved preboot provisioning bundle to $provisioning_path"

  local device_id device_secret unlock_token
  device_id="$(printf '%s\n' "$preboot_bundle" | json_get deviceId)"
  device_secret="$(printf '%s\n' "$preboot_bundle" | json_get deviceSecret)"
  unlock_token="$(printf '%s\n' "$preboot_bundle" | json_get unlockToken)"

  write_preboot_conf "$preboot_server_url" "$device_id" "$device_secret" "$unlock_profile"
  install_preboot_runtime

  local agent_server_url="${COREPOST_AGENT_SERVER_URL:-}"
  if [ -z "$agent_server_url" ]; then
    read_prompt_optional agent_server_url "Agent server base URL (empty = same as preboot)"
  fi
  local agent_server_url_effective="$preboot_server_url"
  if [ -n "$agent_server_url" ]; then
    agent_server_url_effective="$agent_server_url"
  fi

  local agent_device_id="" agent_device_secret=""
  if [ "$agent_server_url_effective" = "$preboot_server_url" ]; then
    agent_device_id="$device_id"
    agent_device_secret="$device_secret"
    save_provisioning_bundle "$agent_provisioning_path" "$preboot_bundle" || true
  else
    local agent_admin_token="${COREPOST_AGENT_ADMIN_TOKEN:-}"
    if [ -z "$agent_admin_token" ]; then
      read_secret agent_admin_token "Agent admin token (leave empty to reuse preboot token)"
      if [ -z "$agent_admin_token" ]; then
        agent_admin_token="$preboot_admin_token"
      fi
    fi
    local agent_bundle
    agent_bundle="$(register_device "$agent_server_url_effective" "$agent_admin_token" "$unlock_profile" "")"
    save_provisioning_bundle "$agent_provisioning_path" "$agent_bundle"
    agent_device_id="$(printf '%s\n' "$agent_bundle" | json_get deviceId)"
    agent_device_secret="$(printf '%s\n' "$agent_bundle" | json_get deviceSecret)"
  fi

  install_agent_stub "$agent_server_url_effective" "$agent_device_id" "$agent_device_secret"

  if confirm "Create a demo LUKS device and validate decrypt now?" ; then
    local user_password=""
    read_secret user_password "User password for demo LUKS (will not be stored)"
    [ -n "$user_password" ] || die "empty password not allowed"
    vm_demo_clean
    vm_demo_prepare_luks "$user_password" "$unlock_token"
    vm_demo_run_preboot "$user_password"
  else
    log "Skipping demo validation"
  fi

  log "Install complete"
}

cmd_reconfigure() {
  require_root
  require_cmd curl
  require_cmd openssl
  require_cmd sed

  ensure_dirs

  local existing_preboot_server_url=""
  existing_preboot_server_url="${COREPOST_PREBOOT_SERVER_URL:-${COREPOST_SERVER_URL:-}}"
  if [ -z "$existing_preboot_server_url" ]; then
    existing_preboot_server_url="$(conf_get "$preboot_conf" COREPOST_SERVER_URL || true)"
  fi

  local preboot_server_url=""
  if [ -n "$existing_preboot_server_url" ]; then
    read_prompt preboot_server_url "Preboot server base URL (scheme://host:port)" "$existing_preboot_server_url"
  else
    read_prompt preboot_server_url "Preboot server base URL (scheme://host:port)"
  fi

  local preboot_bundle=""
  if preboot_bundle="$(load_provisioning_bundle "$provisioning_path")"; then
    :
  else
    log "No preboot provisioning bundle found at $provisioning_path"
    log "Reconfigure can still refresh runtime, but it cannot rewrite config without a bundle."
    preboot_bundle=""
  fi

  if confirm "Re-register device on server (rotate secrets)?" ; then
    local preboot_admin_token="${COREPOST_PREBOOT_ADMIN_TOKEN:-${COREPOST_ADMIN_TOKEN:-}}"
    if [ -z "$preboot_admin_token" ]; then
      read_secret preboot_admin_token "Preboot admin token"
    fi

    local unlock_profile="2fa"
    local usb_key_id=""
    if confirm "Enable 3FA (requires a removable device labeled COREPOST_USB)?" ; then
      unlock_profile="3fa"
      usb_key_id="corepost-usb-$(rand_hex 8)"
      setup_3fa_usb_factor
    fi

    preboot_bundle="$(register_device "$preboot_server_url" "$preboot_admin_token" "$unlock_profile" "$usb_key_id")"
    save_provisioning_bundle "$provisioning_path" "$preboot_bundle"
    log "Saved preboot provisioning bundle to $provisioning_path"
  fi

  if [ -n "$preboot_bundle" ]; then
    local device_id device_secret unlock_profile
    device_id="$(printf '%s\n' "$preboot_bundle" | json_get deviceId)"
    device_secret="$(printf '%s\n' "$preboot_bundle" | json_get deviceSecret)"
    unlock_profile="$(printf '%s\n' "$preboot_bundle" | json_get unlockProfile || true)"
    if [ -z "$unlock_profile" ]; then
      unlock_profile="$(conf_get "$preboot_conf" COREPOST_UNLOCK_PROFILE || true)"
      unlock_profile="${unlock_profile:-2fa}"
    fi
    write_preboot_conf "$preboot_server_url" "$device_id" "$device_secret" "$unlock_profile"
  else
    log "Keeping existing $preboot_conf (not rewriting, bundle missing)"
  fi

  install_preboot_runtime

  local existing_agent_server_url="${COREPOST_AGENT_SERVER_URL:-}"
  if [ -z "$existing_agent_server_url" ] && [ -f "$agent_env_path" ]; then
    existing_agent_server_url="$(conf_get "$agent_env_path" COREPOST_SERVER_URL || true)"
  fi

  local agent_server_url="${existing_agent_server_url:-}"
  if [ -z "$agent_server_url" ]; then
    read_prompt_optional agent_server_url "Agent server base URL (empty = same as preboot)"
  fi
  local agent_server_url_effective="$preboot_server_url"
  if [ -n "$agent_server_url" ]; then
    agent_server_url_effective="$agent_server_url"
  fi

  local agent_bundle="" agent_device_id="" agent_device_secret=""
  if [ "$agent_server_url_effective" = "$preboot_server_url" ]; then
    agent_bundle="$preboot_bundle"
    if [ -z "$agent_bundle" ]; then
      agent_bundle="$(load_provisioning_bundle "$provisioning_path" 2>/dev/null || true)"
    fi
  else
    agent_bundle="$(load_provisioning_bundle "$agent_provisioning_path" 2>/dev/null || true)"
  fi

  if [ -n "$agent_bundle" ]; then
    agent_device_id="$(printf '%s\n' "$agent_bundle" | json_get deviceId || true)"
    agent_device_secret="$(printf '%s\n' "$agent_bundle" | json_get deviceSecret || true)"
  fi

  if [ -z "$agent_device_id" ] || [ -z "$agent_device_secret" ]; then
    if confirm "Register (or re-register) a device on the agent server now?" ; then
      local agent_admin_token="${COREPOST_AGENT_ADMIN_TOKEN:-}"
      if [ -z "$agent_admin_token" ]; then
        read_secret agent_admin_token "Agent admin token (leave empty to reuse preboot token)"
        if [ -z "$agent_admin_token" ]; then
          agent_admin_token="${COREPOST_PREBOOT_ADMIN_TOKEN:-${COREPOST_ADMIN_TOKEN:-}}"
        fi
      fi
      local unlock_profile="${COREPOST_UNLOCK_PROFILE:-2fa}"
      local new_agent_bundle
      new_agent_bundle="$(register_device "$agent_server_url_effective" "$agent_admin_token" "$unlock_profile" "")"
      save_provisioning_bundle "$agent_provisioning_path" "$new_agent_bundle"
      agent_device_id="$(printf '%s\n' "$new_agent_bundle" | json_get deviceId)"
      agent_device_secret="$(printf '%s\n' "$new_agent_bundle" | json_get deviceSecret)"
    fi
  fi

  install_agent_stub "$agent_server_url_effective" "$agent_device_id" "$agent_device_secret"

  log "Reconfigure complete"
}

cmd_uninstall() {
  require_root
  log "Removing installed files..."

  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable --now corepost-agent.service >/dev/null 2>&1 || true
    rm -f /etc/systemd/system/corepost-agent.service || true
    systemctl daemon-reload >/dev/null 2>&1 || true
  fi
  rm -rf /usr/local/lib/corepost-agent || true
  rm -f "$agent_env_path" || true

  rm -f /etc/initramfs-tools/hooks/corepost-preboot || true
  rm -f /etc/initramfs-tools/scripts/local-top/corepost-preboot || true
  rm -f "$preboot_conf" || true

  if command -v update-initramfs >/dev/null 2>&1; then
    update-initramfs -u >/dev/null 2>&1 || true
  fi

  vm_demo_clean
  rm -rf "$state_dir" "$runtime_dir" || true

  log "Uninstall complete"
}

usage() {
  cat >&2 <<'EOF'
Usage:
  ./install.sh install
  ./install.sh reconfigure
  ./install.sh uninstall

Environment variables (optional):
  COREPOST_PREBOOT_SERVER_URL Preboot server base URL (scheme://host:port)
  COREPOST_PREBOOT_ADMIN_TOKEN Preboot admin token for /admin/register
  COREPOST_AGENT_SERVER_URL   Agent server base URL (scheme://host:port). If empty, single-server mode is used.
  COREPOST_AGENT_ADMIN_TOKEN  Agent admin token for /admin/register (only needed for dedicated agent server)
  COREPOST_SERVER_URL        Backward-compatible alias for COREPOST_PREBOOT_SERVER_URL
  COREPOST_ADMIN_TOKEN       Backward-compatible alias for COREPOST_PREBOOT_ADMIN_TOKEN

  COREPOST_GITHUB_ORG        GitHub org/user (default: CorePost)
  COREPOST_GITHUB_RAW_HOST   Raw host (default: raw.githubusercontent.com)
  COREPOST_PREBOOT_REPO      Preboot repo name (default: corepost-preboot)
  COREPOST_PREBOOT_REF       Preboot ref (default: main)
  COREPOST_AGENT_REPO        Agent repo name (default: corepost-agent)
  COREPOST_AGENT_REF         Agent ref (default: main)

  COREPOST_STATE_DIR         State dir (default: /var/lib/corepost-install)
  COREPOST_PROVISIONING_JSON Provisioning bundle path (default: /var/lib/corepost-install/provisioning.json)
  COREPOST_AGENT_PROVISIONING_JSON Agent provisioning bundle path (default: /var/lib/corepost-install/agent-provisioning.json)
  COREPOST_PREBOOT_CONF      Preboot config path (default: /etc/corepost-preboot.conf)
  COREPOST_AGENT_ENV         Agent env path (default: /etc/corepost-agent.env)
EOF
}

main() {
  local cmd="${1:-}"
  case "$cmd" in
    install) shift; cmd_install "$@" ;;
    reconfigure) shift; cmd_reconfigure "$@" ;;
    uninstall) shift; cmd_uninstall "$@" ;;
    ""|-h|--help|help) usage ;;
    *) usage; exit 2 ;;
  esac
}

main "$@"
